services:
  db:
    image: postgres:15
    container_name: interview_db
    environment:
      POSTGRES_DB: interviews
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: interview_backend
    env_file:
      - ./backend/.env
    environment:
      # If DATABASE_URL not provided in env file, fallback to db service
      DATABASE_URL: ${DATABASE_URL:-postgresql+psycopg://postgres:postgres@db:5432/interviews}
      BACKEND_CORS_ORIGINS: ${BACKEND_CORS_ORIGINS:-http://localhost:5173}
    ports:
      - "8001:8000"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: interview_frontend
    env_file:
      - ./frontend/.env
    environment:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL:-http://localhost:8001}
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data: 